"""Add is_sent to Messages

Revision ID: 08496b8b0ba4
Revises: 60a87083bf02
Create Date: 2024-03-05 18:43:54.821620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08496b8b0ba4'
down_revision = '60a87083bf02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('is_sent')

    # ### end Alembic commands ###
