"""add friendship.is_active relationship to Inboxes

Revision ID: 60a87083bf02
Revises: 7320c43954b3
Create Date: 2024-03-05 16:29:36.062688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a87083bf02'
down_revision = '7320c43954b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friendship_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_inboxes_friendship_id_friendships'), 'friendships', ['friendship_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inboxes_friendship_id_friendships'), type_='foreignkey')
        batch_op.drop_column('friendship_id')

    # ### end Alembic commands ###
