"""Clarify Relationships between User & Inbox

Revision ID: a45a4ff50d33
Revises: cdb1acb94a51
Create Date: 2024-02-25 09:48:16.773262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45a4ff50d33'
down_revision = 'cdb1acb94a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inboxes_first_message_id_messages', type_='foreignkey')
        batch_op.drop_constraint('fk_inboxes_last_message_id_messages', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_inboxes_last_message_id_messages', 'messages', ['last_message_id'], ['id'])
        batch_op.create_foreign_key('fk_inboxes_first_message_id_messages', 'messages', ['first_message_id'], ['id'])

    # ### end Alembic commands ###
