"""Add Unique Constraints to Friendship

Revision ID: aaba62a955d5
Revises: dd29eacef754
Create Date: 2024-02-25 14:10:29.198112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaba62a955d5'
down_revision = 'dd29eacef754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_unique_constraint('_users_friendship_uc', ['user1_id', 'user2_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_constraint('_users_friendship_uc', type_='unique')

    # ### end Alembic commands ###
