"""first and last message

Revision ID: cdb1acb94a51
Revises: f3fd8cf2dc51
Create Date: 2024-02-22 22:35:40.181480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb1acb94a51'
down_revision = 'f3fd8cf2dc51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_inboxes_first_message_id_messages'), 'messages', ['first_message_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_inboxes_last_message_id_messages'), 'messages', ['last_message_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_inbox_id_inboxes', type_='foreignkey')
        batch_op.drop_column('inbox_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inbox_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_messages_inbox_id_inboxes', 'inboxes', ['inbox_id'], ['id'])

    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inboxes_last_message_id_messages'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_inboxes_first_message_id_messages'), type_='foreignkey')

    # ### end Alembic commands ###
