"""Add Unique Constraint to Inbox

Revision ID: dd29eacef754
Revises: a45a4ff50d33
Create Date: 2024-02-25 13:43:31.325382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd29eacef754'
down_revision = 'a45a4ff50d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_contact_uc', ['user_id', 'contact_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.drop_constraint('_user_contact_uc', type_='unique')

    # ### end Alembic commands ###
