"""Messages add child_message_id

Revision ID: f3fd8cf2dc51
Revises: f483242125ef
Create Date: 2024-02-22 21:11:32.104931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fd8cf2dc51'
down_revision = 'f483242125ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_message_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inbox_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_messages_inbox_id_inboxes'), 'inboxes', ['inbox_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_messages_child_message_id_messages'), 'messages', ['child_message_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_child_message_id_messages'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_messages_inbox_id_inboxes'), type_='foreignkey')
        batch_op.drop_column('inbox_id')
        batch_op.drop_column('child_message_id')

    # ### end Alembic commands ###
