"""Inbox Foreign Keys

Revision ID: f483242125ef
Revises: 44b0165807ab
Create Date: 2024-02-22 12:42:47.640374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f483242125ef'
down_revision = '44b0165807ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_inboxes_contact_user_id_users'), 'users', ['contact_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_inboxes_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inboxes_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_inboxes_contact_user_id_users'), type_='foreignkey')

    # ### end Alembic commands ###
